<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.1" />
    <PackageReference Include="Otus.QueueDto" Version="1.0.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\AuctionTrading.Common.Infrastructure.Queues.Abstraction\AuctionTrading.Common.Infrastructure.Queues.Abstraction.csproj" />
    <ProjectReference Include="..\AuctionTrading.Infrastructure.MediatR\AuctionTrading.Infrastructure.MediatR.csproj" />
  </ItemGroup>

</Project>
